version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    image: 'postgres:9.6-alpine'
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
    volumes: 
      - data:/var/lib/postgresql/data
    networks:
      - app-tier
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - app-tier
  myapp:
    image: 'servian/techchallengeapp:latest'
    restart: always
    depends_on:
      - postgresql
    ports:
      - 8080:3000
    environment:
      VTT_DBUSER: ${VTT_DBUSER}
      VTT_DBPASSWORD: ${VTT_DBPASSWORD}
      VTT_DBNAME: ${VTT_DBNAME}
      VTT_DBPORT: ${VTT_DBPORT}
      VTT_DBHOST: ${VTT_DBHOST}
      VTT_LISTENHOST: ${VTT_LISTENHOST}
      VTT_LISTENPORT: ${VTT_LISTENPORT}
    command:
        serve && updatedb
    networks:
      - app-tier
  myappdb:
    image: 'servian/techchallengeapp:latest'
    restart: always
    depends_on:
      - postgresql
    environment:
      VTT_DBUSER: ${VTT_DBUSER}
      VTT_DBPASSWORD: ${VTT_DBPASSWORD}
      VTT_DBNAME: ${VTT_DBNAME}
      VTT_DBPORT: ${VTT_DBPORT}
      VTT_DBHOST: ${VTT_DBHOST}
      VTT_LISTENHOST: ${VTT_LISTENHOST}
      VTT_LISTENPORT: ${VTT_LISTENPORT}
    command:
        updatedb 
    networks:
      - app-tier
volumes:
  data:
    driver: local
