name: vagrant-up

on:
  push:
    branches:
    - master
    - localdev
  pull_request:
    branches:
    - master

jobs:
  vagrant-up:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
    
    - name: Run vagrant validate
      run: vagrant validate

    - name: Run vagrant up
      run: vagrant up

    - name: curl healthcheck command
      run: curl http://localhost:8080/healthcheck/      
    
    - name: curl task command
      run: curl http://localhost:8080/api/task/      
    
    - name: ssh into box after boot
      run: vagrant ssh -c "echo 'hello world!'"
    
    - name: ssh into box after boot
      run: vagrant ssh -c "docker ps -a"

    # - name: vagrant destroy
    #   run: vagrant destroy
