name: vagrant-up

on:
  push:
    branches:
    - master
    - localdev
    paths:
      - "Vagrant/**"
  pull_request:
    branches:
    - master
    paths:
      - "Vagrant/**"

jobs:
  vagrant-up:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Run vagrant validate
      run: cd Vagrant && vagrant validate

    - name: Run vagrant up
      run:  cd Vagrant && vagrant up
         
    - name: ssh into box after boot
      run: cd Vagrant && vagrant ssh -c "echo 'hello world!'"
    
    - name: ssh and docker list into box to check containers
      run: cd Vagrant && vagrant ssh -c "docker ps -a"

    - name: curl healthcheck command
      run: curl http://127.0.0.1:8080/healthcheck/      
    
    - name: curl task command
      run: curl http://127.0.0.1:8080/api/task/ 

    # - name: vagrant destroy
    #   run: vagrant destroy
